# -*- coding: utf-8 -*-
"""practical no 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MZASm-Z-IOXW4miiZLrf5fdoENBNL-PH
"""

import time
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data[:, :2]  # Take only the first two features (petal length and width)
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an SVM classifier
svm_classifier = svm.SVC(kernel='linear')

# Train the classifier on the training data
start_time = time.time()
svm_classifier.fit(X_train, y_train)
training_time = time.time() - start_time

# Make predictions on the test data
start_time = time.time()
y_pred = svm_classifier.predict(X_test)
prediction_time = time.time() - start_time

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Training Time (seconds):", training_time)
print("Prediction Time (seconds):", prediction_time)