# -*- coding: utf-8 -*-
"""practical no 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U0_43p5FtdxXSFip3x4cKlxJk4LJBRfg
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm


digits = datasets.load_digits()


X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=42)


classifier = svm.SVC()


classifier.fit(X_train, y_train)


predicted = classifier.predict(X_test)


accuracy = np.mean(predicted == y_test)
print("Accuracy:", accuracy)

fig, axes = plt.subplots(4, 4, figsize=(8, 8))
for i, ax in enumerate(axes.flat):
    ax.imshow(X_test[i].reshape(8, 8), cmap='gray')
    ax.set_title("Predicted: %d" % predicted[i])
    ax.axis('off')

plt.show()